### ISSUE TITLE
Storybook dev environment

### ISSUE THREAD

**Issue by DHedgecock** [crystal-ball/componentry#102]
## Storybook development workflow

The dev tooling for Componentry is in transition from the documentation site to a set of Storybook stories. _(The primary motivation for this is being able to work on components in a more focused scope during development, with the docs site sometimes unrelated issues slow down dev work)_

- [x] Add Storybook deps and configs to project
- [ ] Create Storybook stories for Active, Core, Form, Provider, and Inform component groups
- [ ] Add knobs to stories for testing different props
- [x] Update the `CONTRIBUTING` guide on running Storybook for development

Other possible enhancements: knob for theme, styles manipulation, docs addon

**Comment by DHedgecock** [comment]
Componentry dev environment using Storybook is complete 🎉
