### ISSUE TITLE
✅ Comprehensive Test Suite

### ISSUE THREAD

**Issue by DHedgecock** [crystal-ball/componentry#12]
Upgrade existing test suite to establish a comprehensive library suite that is le-git.

## Tests

- [ ] Activation user interactions for all active componets
- [ ] Visual diffing tests with Puppeteer and Storybook
- [ ] Snapshot tests created for all components for reference

**Comment by DHedgecock** [comment]
Library has a good base of unit tests created and screenshot testing is now supported with Chromatic.
