### ISSUE TITLE
📝 A++ Documentation

### ISSUE THREAD

**Issue by DHedgecock** [crystal-ball/componentry#50]
Provide comprehensive documentation needed to use library. 

### General docs
- [ ] README includes library description, benefits, and an example component usage
- [ ] Demo site landing page highlights library key benefits and design principles
- [ ] Motivation: Why another Bootstrap component library? (modularity of Bootstrap styles, A++ Accessibility, using a simple component API, exposing pre-wired customizable components for any level of component composition instead of trying to cover all uses cases with huge number of props)
- [ ] Evolution of Bootstrap styles to single component scope pattern
- [ ] Using the `Media` and `Theme` provider components

#### Demo site
- [ ] Getting started library install
- [ ] Setting up library SASS imports with webpack
- [ ] Best practice Icon usage within the library (default styles provided)
- [ ] Icon overrides with svg id references, customizing icons used
- [ ] Theme customization

### Concepts
- [ ] Diagram of how library shares and uses active context to handle active elements, should be useful for people who want to contribute to library.
- [ ] How to control components using passed activate/deactivate/active props, as well as the types of Automated, Observed and Controlled component setups.
- [ ] Document passing active and activeId, how the State component uses the activeId for components with multiple trigger/content sets.
- [ ] Create configurable examples of the shared component APIs and include them in the docs with a checkmark icon for display of list

### Misc docs
- [ ] Dropdown `overlay` direction
- [ ] Update advanced theming with notes on how to override mixins for creating custom styles.
- [ ] Need a section in library architecture/accessibility about focus outlines and suppressing them wholesale for mouse users with the `setup-outline-handlers` utils.
- [ ] Notes on accessibility, including `.sr-only` div in alerts for type...
- [ ] Short list of applicable BS classes for each element for easy reference
- [ ] Importable and configurable checklist of supported library APIs available for each component.
- [ ] Add radio to ListGroup demonstarting anchor and Button examples.
- [ ] Document `BaseButton` and how it's available/used for elements that are classless buttons
- [ ] Add how context is used to pass theme defaults in one of the Concepts guides.

**Comment by DHedgecock** [comment]
No longer needed.
