### ISSUE TITLE
V3 release checklist

### ISSUE THREAD

**Issue by DHedgecock** [crystal-ball/componentry#65]
# Componentry v3 - Mauve

_This issue should be used to track individual work items that are not issues_

## Components

- [ ] Update button styles to use darken map and add disabled outline, background and color

## Documentation

- [ ] Updated install and getting started
- [ ] Using theme provider component
- [ ] New type component APIs and demos
- [ ] Using space props utils
